# Generated by Django 5.2.9 on 2025-12-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('lpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
