# Generated by Django 5.2.9 on 2025-12-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lpa',
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
