# Generated by Django 5.2.9 on 2025-12-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_status_alter_application_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='applied_on',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
